SELECT * FROM POC.FUNCIONARIO F 
INNER JOIN (
SELECT TF1.ID_FUNCIONARIO,TF1.NM_TELEFONE AS TELEFONE1, TF2.NM_TELEFONE AS TELEFONE2, TF3.NM_TELEFONE AS TELEFONE3 
FROM (
SELECT *, 
ROW_NUMBER() OVER (PARTITION BY ID_FUNCIONARIO ORDER BY ID) AS NM_LINHA  
FROM POC.TELEFONE_FUNCIONARIO) AS TF1
LEFT JOIN(
SELECT *, 
ROW_NUMBER() OVER (PARTITION BY ID_FUNCIONARIO ORDER BY ID) AS NM_LINHA  
FROM POC.TELEFONE_FUNCIONARIO)  AS TF2
ON TF1.ID_FUNCIONARIO = TF2.ID_FUNCIONARIO 
AND TF1.NM_LINHA = ISNULL(TF2.NM_LINHA-1,TF1.NM_LINHA)
LEFT JOIN(
SELECT *, 
ROW_NUMBER() OVER (PARTITION BY ID_FUNCIONARIO ORDER BY ID) AS NM_LINHA  
FROM POC.TELEFONE_FUNCIONARIO)  AS TF3
ON TF1.ID_FUNCIONARIO = TF3.ID_FUNCIONARIO
AND TF1.NM_LINHA = ISNULL(TF3.NM_LINHA-2,TF1.NM_LINHA)
WHERE TF1.NM_LINHA = 1) TB2 ON
TB2.ID_FUNCIONARIO = F.ID
